### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by bathedragon** [pgroot/pRadius#2]
你好，按照Guide安装成功以后用什么用户名登录？

**Comment by pgroot** [comment]
没有初始值，暂时停用Middleware/Administrator，然后自己添加

**Comment by bathedragon** [comment]
OK，我用数据库后台直接添加了email和pass，密码是明文的吧。
目前还是不行，我在operator表中添加了用户名的密码，登录提示帐户或者密码错误。

**Comment by pgroot** [comment]
不是明文，Hash::make

**Comment by bathedragon** [comment]
呃，  现在是我能够进入首页，也能通过账号申请看到member_apply表中密码是明文的，不过同样无法登录。我按照你的安装说明已经能够进入网站程序，但是现在无法进入后台，能告诉我后面怎么操作吗？

**Comment by pgroot** [comment]
那个是FreeRADIUS的账号，vpn帐号，密码是明文的了
停用Middleware/Administrator（return redirect注释掉），然后访问 /admin/operator/create添加管理账号

**Comment by bathedragon** [comment]
明白了，但是还是会跳转。
#        if( ! in_array($this->role,['admin'])) {
#            return redirect()->away("/session/new");
